### ISSUE TITLE
tasckat action always exits with error code 0

### ISSUE THREAD

**Issue by ShahradR** [ShahradR/action-taskcat#10]
As part of #5, taskcat output was piped to `cat` to disable reprint's multi-line output functionality, by tricking it into believing that it wasn't printing to a terminal. The resulting command is:

```
taskcat test run | cat
```

However, because `cat` is the last command in the pipeline, it always exits with return code 0, and taskcat failures are masked.

**Comment by muktadadariya** [comment]
Can I use pipefail with "taskcat test clean "?

**Comment by ShahradR** [comment]
>
>
> Can I use pipefail with "taskcat test clean "?

@muktadadariya I think that should work! The `pipefail` option controls which exit codes are returned in Bash pipelines – as long as `taskcat` returns a non-zero exit code, `pipefail` should be able to catch that.

For your specific example, we can run `taskcat test clean ALL | echo "Hello World"` in a scenario where `taskcat` returns an error (in my case, I enabled termination protection on the stack). When `pipefail` isn't set, we won't catch the error because `echo "Hello World"` runs last and always returns `0`. Once set, `taskcat`'s exit code of `1` is returned by the pipeline instead.

**Running pipeline _without_ the `pipefail` option set**
[![asciicast](https://asciinema.org/a/WTYezWhjOCIv7Oz0496lywtn0.svg)](https://asciinema.org/a/WTYezWhjOCIv7Oz0496lywtn0)

**Running pipeline _with_ the `pipefail` option set**
[![asciicast](https://asciinema.org/a/q4WbamPFNiuQq5Ulh5OpHcNIc.svg)](https://asciinema.org/a/q4WbamPFNiuQq5Ulh5OpHcNIc)

For more info on the subject, [Tom Van Eyck's blog post](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/) details the `pipefail` option along with a bunch of other ones you can set to make your shell scripts more robust. You can also take a look at the ["Pipelines" section of the Bash reference manual](https://www.gnu.org/software/bash/manual/html_node/Pipelines.html) for information on Bash pipelines in general. Hope this helps!
